name: hro
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  google_fonts: ^2.0.0
  firebase_auth: ^1.1.3
  firebase_core: ^1.1.0
  firebase_storage: ^8.1.0
  font_awesome_flutter: ^9.0.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^5.0.2
  splash_screen_view: ^3.0.0
  image_picker: ^0.7.5
  http: ^0.13.3
  toast: ^0.1.5
  time_range_picker: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  numberpicker: ^2.1.1
  liquid_pull_to_refresh: ^3.0.0
  cloud_firestore: ^2.2.0
  google_maps_flutter: ^2.0.6
  location: ^4.1.1
  geolocator: ^7.2.0+1
  geocoder: ^0.2.1
  intl: ^0.17.0
  badges: ^2.0.1
  firebase_messaging: ^10.0.0
  material_design_icons_flutter: ^4.0.5955
  flutter_launcher_icons: ^0.9.0
  location_permissions: ^4.0.0
  anim_search_bar: ^2.0.2
  focused_menu: ^1.0.5






  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/hroLogo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/hroLogo.png
    - assets/images/googleLogo.png
    - assets/images/hroLogoThai.png
    - assets/images/person-icon.png
    - assets/images/shop-icon.png
    - assets/images/food_icon.png
    - assets/images/map.png
    - assets/images/loading.gif



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
         - asset: assets/fonts/Prompt-Regular.ttf
         - asset: assets/fonts/Prompt-Italic.ttf
           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
